# =========================================================
# OUTPUT
# =========================================================

output {
  elasticsearch {
    hosts               => ["https://es01:9200"]
    user                => "elastic"
    password            => "projetoCyber12"
    ssl_certificate_authorities => ["/usr/share/elasticsearch/config/certs/ca/ca.crt"]
    index               => "%{[@metadata][index_prefix]}-%{+YYYY.MM.dd}"
  }

  # Descomente para depurar no console enquanto ajusta os filtros
  # stdout { codec => rubydebug }
}
